# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "shell", inline: <<-SHELL
    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    echo 'deb https://pkg.jenkins.io/debian-stable binary/' >> /etc/apt/sources.list
    apt-get update
    apt-get install -y openjdk-8-jdk
    apt-get install -y jenkins    
  SHELL
end
